### ISSUE TITLE
Extension host crashed

### ISSUE THREAD

**Issue by ronilaukkarinen** [swdotcom/swdc-vscode#113]
**Describe the bug**
Extentsion host crashes

```
events.js:180      throw er; // Unhandled 'error' event      ^Error: socket hang up    at connResetException (internal/errors.js:559:14)    at TLSSocket.socketOnEnd (_http_client.js:433:23)    at TLSSocket.emit (events.js:208:15)    at endReadableNT (_stream_readable.js:1168:12)    at processTicksAndRejections (internal/process/task_queues.js:77:11)Emitted 'error' event at:    at H.onRequestError (/Users/rolle/Projects/vscode-settings/.vscode/extensions/softwaredotcom.swdc-vscode-2.2.31/dist/extension.js:462:12993)    at ClientRequest.emit (events.js:208:15)    at TLSSocket.socketOnEnd (_http_client.js:433:9)    at TLSSocket.emit (events.js:208:15)    at endReadableNT (_stream_readable.js:1168:12)    at processTicksAndRejections (internal/process/task_queues.js:77:11) {  code: 'ECONNRESET'}
```

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**
1. Install extension
2. See crash

**Screenshots**
https://dsh.re/490b4

**Desktop (please complete the following information):**
 - OS: macOS Catalina (10.15.4)
 - Code Time 2.2.31
 - VSCode 1.47.1

**Comment by xavluiz** [comment]
Thank you for the issue report. The error looks like a connection was closed abruptly. We're looking into the app now and will provide an update as soon as we can.

**Comment by xavluiz** [comment]
We've fixed the timeout issue our app was causing. Let us know if you have any other issues and thank you again for the update on this. Regards.

**Comment by dnarvaez27** [comment]
I'm still having the same issue.

**Desktop**  
OS: Windows 10 (version 2004. build 19041.388)
Code Time 2.2.32
VSCode 1.47.2

![SharedScreenshot](https://user-images.githubusercontent.com/12243937/87879058-e6631600-c9ad-11ea-8640-663a5a1d4cde.jpg)

**Comment by HamzaAnis** [comment]
Still having the same issue on macOS Catalina 10.15.3
<img width="1440" alt="Screen Shot 2020-07-20 at 4 41 59 PM" src="https://user-images.githubusercontent.com/18266623/87934241-1d1d5700-caa8-11ea-8981-ea3b86724275.png">
<img width="1440" alt="Screen Shot 2020-07-20 at 4 42 36 PM" src="https://user-images.githubusercontent.com/18266623/87934260-24dcfb80-caa8-11ea-981d-137ea72794b4.png">

**Comment by HamzaAnis** [comment]
*Bump*

**Comment by Ahmeed2m** [comment]
_same issue_

**Comment by HamzaAnis** [comment]
Please look into this issue. Thank you.

**Comment by brettmstevens7** [comment]
Sorry about this issue. We ran into some unexpected downtime. The latest version (v2.2.34) was just recently pushed to the marketplace with a fix for this issue.

**Comment by HamzaAnis** [comment]
Yes it is working now. Will update after some more testing. Thank you.

**Comment by Ahmeed2m** [comment]
> Sorry about this issue. We ran into some unexpected downtime. The latest version (v2.2.34) was just recently pushed to the marketplace with a fix for this issue.
@brettmstevens7 
Still, 

```
events.js:180      throw er; // Unhandled 'error' event      ^[Error: Client network socket disconnected before secure TLS connection was established	at connResetException (internal/errors.js:559:14)	at TLSSocket.onConnectEnd (_tls_wrap.js:1357:19)	at Object.onceWrapper (events.js:291:20)	at TLSSocket.emit (events.js:208:15)	at endReadableNT (_stream_readable.js:1168:12)	at processTicksAndRejections (internal/process/task_queues.js:77:11)Emitted 'error' event at:	at H.onRequestError (/home/ahmed/.vscode/extensions/softwaredotcom.swdc-vscode-2.2.35/dist/extension.js:462:12993)	at ClientRequest.emit (events.js:208:15)	at TLSSocket.socketErrorListener (_http_client.js:399:9)	at TLSSocket.emit (events.js:203:13)	at emitErrorNT (internal/streams/destroy.js:91:8)	at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)	at processTicksAndRejections (internal/process/task_queues.js:77:11)] {  code: 'ECONNRESET',  path: null,  host: 'com-software-prod1.collector.snplow.net',  port: 443,  localAddress: undefined,  vslsStack: [    CallSite {},    CallSite {},    CallSite {},    CallSite {},    CallSite {},    CallSite {}  ]}
```

**Comment by Ahmeed2m** [comment]
The extension is ironically making me unproductive for the pas week or so. The opposite of what you're claiming to do.

**Comment by HamzaAnis** [comment]
> > Sorry about this issue. We ran into some unexpected downtime. The latest version (v2.2.34) was just recently pushed to the marketplace with a fix for this issue.
> 
> @brettmstevens7
> Still,
> This is with version 2.2.35 !
> 
> ```
> events.js:180
>       throw er; // Unhandled 'error' event
>       ^
> 
> [Error: Client network socket disconnected before secure TLS connection was established
> 	at connResetException (internal/errors.js:559:14)
> 	at TLSSocket.onConnectEnd (_tls_wrap.js:1357:19)
> 	at Object.onceWrapper (events.js:291:20)
> 	at TLSSocket.emit (events.js:208:15)
> 	at endReadableNT (_stream_readable.js:1168:12)
> 	at processTicksAndRejections (internal/process/task_queues.js:77:11)
> Emitted 'error' event at:
> 	at H.onRequestError (/home/ahmed/.vscode/extensions/softwaredotcom.swdc-vscode-2.2.35/dist/extension.js:462:12993)
> 	at ClientRequest.emit (events.js:208:15)
> 	at TLSSocket.socketErrorListener (_http_client.js:399:9)
> 	at TLSSocket.emit (events.js:203:13)
> 	at emitErrorNT (internal/streams/destroy.js:91:8)
> 	at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
> 	at processTicksAndRejections (internal/process/task_queues.js:77:11)] {
>   code: 'ECONNRESET',
>   path: null,
>   host: 'com-software-prod1.collector.snplow.net',
>   port: 443,
>   localAddress: undefined,
>   vslsStack: [
>     CallSite {},
>     CallSite {},
>     CallSite {},
>     CallSite {},
>     CallSite {},
>     CallSite {}
>   ]
> }
> ﻿```
> ```

I am not having this bug now on `v 2.2.35`

**Comment by HamzaAnis** [comment]
@Ahmeed2m make sure it is updated to latest version.

**Comment by brettmstevens7** [comment]
Sorry @Ahmeed2m, can you confirm that it is no longer happening on 2.2.35? It could have been that you had an old project window that was not reloaded, but let me know if the issue persists for you.

**Comment by HamzaAnis** [comment]
> Sorry @Ahmeed2m, can you confirm that it is no longer happening on 2.2.35? It could have been that you had an old project window that was not reloaded, but let me know if the issue persists for you.

Issue persists.

**Comment by Ahmeed2m** [comment]
@brettmstevens7  It still happens in v2.2.38. Just a minute ago it happened. 
Again the logs if it would help

```
events.js:180
      throw er; // Unhandled 'error' event
      ^

[Error: Client network socket disconnected before secure TLS connection was established
	at connResetException (internal/errors.js:559:14)
	at TLSSocket.onConnectEnd (_tls_wrap.js:1357:19)
	at Object.onceWrapper (events.js:291:20)
	at TLSSocket.emit (events.js:208:15)
	at endReadableNT (_stream_readable.js:1168:12)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)
Emitted 'error' event at:
	at H.onRequestError (/home/ahmed/.vscode/extensions/softwaredotcom.swdc-vscode-2.2.38/dist/extension.js:462:12993)
	at ClientRequest.emit (events.js:208:15)
	at TLSSocket.socketErrorListener (_http_client.js:399:9)
	at TLSSocket.emit (events.js:203:13)
	at emitErrorNT (internal/streams/destroy.js:91:8)
	at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)] {
  code: 'ECONNRESET',
  path: null,
  host: 'com-software-prod1.collector.snplow.net',
  port: 443,
  localAddress: undefined,
  vslsStack: [
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {}
  ]
}
```

**Comment by xavluiz** [comment]
These logs are helpful, thank you. It looks like a new endpoint causing the TCP conversation to abruptly close. I'll look into this now and provide a response as soon as I can. Thank you for this update.

**Comment by HamzaAnis** [comment]
@xavluiz Yes please. All of the extensions needs to be restarted after the crash  which is very annoying. I have it disabled since after `v2.3.8`.

**Comment by ronilaukkarinen** [comment]
Still having this issue. Happened just now.

![Screenshot](https://i.imgur.com/ZZGIYFd.png)

```
events.js:180      throw er; // Unhandled 'error' event      ^Error: socket hang up    at connResetException (internal/errors.js:559:14)    at TLSSocket.socketOnEnd (_http_client.js:433:23)    at TLSSocket.emit (events.js:208:15)    at endReadableNT (_stream_readable.js:1168:12)    at processTicksAndRejections (internal/process/task_queues.js:77:11)Emitted 'error' event at:    at H.onRequestError (/Users/rolle/Projects/vscode-settings/.vscode/extensions/softwaredotcom.swdc-vscode-2.2.41/dist/extension.js:462:12993)    at ClientRequest.emit (events.js:208:15)    at TLSSocket.socketOnEnd (_http_client.js:433:9)    at TLSSocket.emit (events.js:208:15)    at endReadableNT (_stream_readable.js:1168:12)    at processTicksAndRejections (internal/process/task_queues.js:77:11) {  code: 'ECONNRESET'}
```

**Comment by HamzaAnis** [comment]
I don't want to uninstall this but I am uninstalling it since the issue is fixed.

**Comment by HamzaAnis** [comment]
I don't want to uninstall this but I am uninstalling it until this bug can not be fixed.

**Comment by Ahmeed2m** [comment]
I already uninstalled 5 days ago. My work was frequently stopped from this

**Comment by brettmstevens7** [comment]
@ronilaukkarinen are you still encountering the issue? It did persist in `v2.2.38`. It would be helpful if you could share if you are still seeing this issue or not in `v2.2.41` or above. Also @Ahmeed2m @HamzaAnis. Thank you again and sorry for the inconvenience.

**Comment by HamzaAnis** [comment]
@brettmstevens7 The issue persists in 2.2.42 and the log for me is same [this](https://github.com/swdotcom/swdc-vscode/issues/113#issuecomment-664891216).

**Comment by xavluiz** [comment]
@Ahmeed2m @HamzaAnis @ronilaukkarinen, thank you for your patience with this issue. It was difficult to reproduce as it seems to throw the mentioned errors in rare cases. We have updated our extension library to ensure we catch these possible TCP conversations abruptly closing, along with the EPIPE error that also shows that a response is trying to pipe to a closed stream. We have deployed v2.2.43 to the marketplace and our team is currently running that version as well to verify the fix. We'd love feedback or any other issue details that can help us understand this more.

Thank you

**Comment by Ahmeed2m** [comment]
Seems to be working and fixed. Used it yesterday all day and didn't crash, will report back today if it happens again.

**Comment by HamzaAnis** [comment]
The issue persists and I am permanently uninstalling this and `100 days of code` 😕

**Comment by brettmstevens7** [comment]
@HamzaAnis it might have been related to this bug. We're working on a fix today. https://github.com/swdotcom/swdc-vscode-100-days-of-code/issues/8

**Comment by Ahmeed2m** [comment]
@brettmstevens7 fyi, I never experienced any crash for a week now since my last comment.

**Comment by charlwillia6** [comment]
I also have this issue.  To be clear, it only happens when I am debugging and stop the debugger.  I am also using Remote WSL extensions and using Arch WSL.  The extensions is installed on the local editor and not the remote.  There is not option to install it on the remote.  

It crashes the extension host first, and then the Remote: WSL connection breaks and I have to reload the window.  

This is happening with version 2.2.48

![image](https://user-images.githubusercontent.com/9610352/90067266-d98bc680-dcbc-11ea-9c1d-a03d380dde2e.png)

**Comment by HamzaAnis** [comment]
In my case it happens when I open the git extension. Other than that it works fine.

**Comment by mpearon** [comment]
I'm seeing the same behavior when using this [SVN extension](https://github.com/JohnstonCode/svn-scm).

**Comment by kissu** [comment]
Got some insights on that one ? Crashing as of latest version and breaking some other extensions on my side. 😓

**Comment by bjacobson26** [comment]
Hi everyone - this bug should be resolved in the latest 2.3.2 release. If anyone is still experiencing issues, please let us know. Thank you!

**Comment by kissu** [comment]
Still broken as of latest version aka `2.3.6`, rollbacking to `2.2.19`. 😄 
![image](https://user-images.githubusercontent.com/5133074/92002060-b8f4e080-ed3f-11ea-8ec8-480c24b5479a.png)

**Comment by xavluiz** [comment]
@kissu we'll investigate this again, thank you for the trace information.
