### ISSUE TITLE
No data available

### ISSUE THREAD

**Issue by Rishats** [swdotcom/swdc-vscode#13]
I have:
MacOS Mojave
Last version swdc-vscode.
When i try to open code time dashboard i get:
<img width="744" alt="2019-02-26 22 42 54" src="https://user-images.githubusercontent.com/21194702/53430044-ee689180-3a17-11e9-8f6a-3776711a4341.png">

When i try to see dashboards in web, i get white page.

**Comment by keaton185** [comment]
Same issue - unable to login or view data on web dashboard. Seems like a service may be down.

**Comment by andrewhli** [comment]
Apologies for the outage. Due to many new users, we ran into a scaling problem today. We've been working on this and will let you know when it's done.

**Comment by andrewhli** [comment]
The traffic and scaling issues have been resolved, so please let us know if this continues to be an issue.

**Comment by NetworkMonk** [comment]
I'm still having problems, occasionally it works and I can see stats, but most of the time just a blank page.

**Comment by scottwestover** [comment]
I am still having issues as well in vscode, and I am also unable to login or view data on the web dashboard.

**Comment by andrewhli** [comment]
Hi everyone. Thanks for letting us know. We're currently upgrading the database. It looks like the rendering for the web graphics are taking up a lot of space in the DB, and this is the next traffic-related constraint. I'll let you know when the database upgrade is done.

**Comment by andrewhli** [comment]
Hey there. The database upgrade is done, and the app loads much faster now. Please let me know if you see any other problems.

**Comment by andrewhli** [comment]
Hey there. The database upgrade is done, and the app loads much faster now. Please let me know if you see any other problems.

**Comment by andrewhli** [comment]
Hey @Rishats, @keaton185, @NetworkMonk, @scottwestover - we're live on Product Hunt! Would appreciate any support you can give: https://www.producthunt.com/posts/code-time

**Comment by yordanzhelevdev** [comment]
I'm getting the same error.
