### ISSUE TITLE
Crashing Visual Studio 2017

### ISSUE THREAD

**Issue by LeedanJohnson** [swdotcom/swdc-vscode#15]
I've been having issues with Visual Studio 2017 crashing ~1 min after startup. Visual Studio is 100% up-to-date. Disabling the Code Time extension has eliminated the problem. (Tried it several times with the extension enabled and disabled. The issue only exists when the Code Time extension is enabled.)

**Comment by andrewhli** [comment]
Hi there. Appreciate your note and apologies for wasting your time. This bug was related to the high traffic issue we've been experiencing. The traffic and scaling issues have been resolved, so please let us know if this continues to be an issue.

**Comment by LeedanJohnson** [comment]
The issue is still occurring for me as of 2 hours ago. I checked for any updated to the Visual Studio 2017 Code Time extension, and found none.

**Comment by andrewhli** [comment]
Hi everyone. Thanks for letting us know. We're currently upgrading the database. It looks like the rendering for the web graphics are taking up a lot of space in the DB, and this is the next traffic-related constraint. I'll let you know when the database upgrade is done.

**Comment by andrewhli** [comment]
Hey there. The database upgrade is done, and the app loads much faster now. Please let me know if you see any other problems.
